// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creationtask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CreationTaskUpdate is the builder for updating CreationTask entities.
type CreationTaskUpdate struct {
	config
	hooks    []Hook
	mutation *CreationTaskMutation
}

// Where appends a list predicates to the CreationTaskUpdate builder.
func (_u *CreationTaskUpdate) Where(ps ...predicate.CreationTask) *CreationTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CreationTaskUpdate) SetUserID(v int64) *CreationTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableUserID(v *int64) *CreationTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreationTaskUpdate) AddUserID(v int64) *CreationTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *CreationTaskUpdate) SetType(v string) *CreationTaskUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableType(v *string) *CreationTaskUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CreationTaskUpdate) SetTitle(v string) *CreationTaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableTitle(v *string) *CreationTaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *CreationTaskUpdate) SetInput(v string) *CreationTaskUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableInput(v *string) *CreationTaskUpdate {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// ClearInput clears the value of the "input" field.
func (_u *CreationTaskUpdate) ClearInput() *CreationTaskUpdate {
	_u.mutation.ClearInput()
	return _u
}

// SetOutput sets the "output" field.
func (_u *CreationTaskUpdate) SetOutput(v string) *CreationTaskUpdate {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableOutput(v *string) *CreationTaskUpdate {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *CreationTaskUpdate) ClearOutput() *CreationTaskUpdate {
	_u.mutation.ClearOutput()
	return _u
}

// SetModel sets the "model" field.
func (_u *CreationTaskUpdate) SetModel(v string) *CreationTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreationTaskUpdate) SetNillableModel(v *string) *CreationTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// Mutation returns the CreationTaskMutation object of the builder.
func (_u *CreationTaskUpdate) Mutation() *CreationTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreationTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreationTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreationTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreationTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreationTaskUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := creationtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreationTask.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := creationtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CreationTask.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creationtask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreationTask.model": %w`, err)}
		}
	}
	return nil
}

func (_u *CreationTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creationtask.Table, creationtask.Columns, sqlgraph.NewFieldSpec(creationtask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(creationtask.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(creationtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(creationtask.FieldInput, field.TypeString, value)
	}
	if _u.mutation.InputCleared() {
		_spec.ClearField(creationtask.FieldInput, field.TypeString)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(creationtask.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(creationtask.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creationtask.FieldModel, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreationTaskUpdateOne is the builder for updating a single CreationTask entity.
type CreationTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreationTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *CreationTaskUpdateOne) SetUserID(v int64) *CreationTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableUserID(v *int64) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreationTaskUpdateOne) AddUserID(v int64) *CreationTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *CreationTaskUpdateOne) SetType(v string) *CreationTaskUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableType(v *string) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CreationTaskUpdateOne) SetTitle(v string) *CreationTaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableTitle(v *string) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *CreationTaskUpdateOne) SetInput(v string) *CreationTaskUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableInput(v *string) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetInput(*v)
	}
	return _u
}

// ClearInput clears the value of the "input" field.
func (_u *CreationTaskUpdateOne) ClearInput() *CreationTaskUpdateOne {
	_u.mutation.ClearInput()
	return _u
}

// SetOutput sets the "output" field.
func (_u *CreationTaskUpdateOne) SetOutput(v string) *CreationTaskUpdateOne {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableOutput(v *string) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *CreationTaskUpdateOne) ClearOutput() *CreationTaskUpdateOne {
	_u.mutation.ClearOutput()
	return _u
}

// SetModel sets the "model" field.
func (_u *CreationTaskUpdateOne) SetModel(v string) *CreationTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreationTaskUpdateOne) SetNillableModel(v *string) *CreationTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// Mutation returns the CreationTaskMutation object of the builder.
func (_u *CreationTaskUpdateOne) Mutation() *CreationTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the CreationTaskUpdate builder.
func (_u *CreationTaskUpdateOne) Where(ps ...predicate.CreationTask) *CreationTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreationTaskUpdateOne) Select(field string, fields ...string) *CreationTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreationTask entity.
func (_u *CreationTaskUpdateOne) Save(ctx context.Context) (*CreationTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreationTaskUpdateOne) SaveX(ctx context.Context) *CreationTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreationTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreationTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreationTaskUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := creationtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreationTask.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := creationtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CreationTask.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creationtask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreationTask.model": %w`, err)}
		}
	}
	return nil
}

func (_u *CreationTaskUpdateOne) sqlSave(ctx context.Context) (_node *CreationTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creationtask.Table, creationtask.Columns, sqlgraph.NewFieldSpec(creationtask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreationTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creationtask.FieldID)
		for _, f := range fields {
			if !creationtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creationtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(creationtask.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(creationtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(creationtask.FieldInput, field.TypeString, value)
	}
	if _u.mutation.InputCleared() {
		_spec.ClearField(creationtask.FieldInput, field.TypeString)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(creationtask.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(creationtask.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creationtask.FieldModel, field.TypeString, value)
	}
	_node = &CreationTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
