// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creationtask"
)

// CreationTaskCreate is the builder for creating a CreationTask entity.
type CreationTaskCreate struct {
	config
	mutation *CreationTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CreationTaskCreate) SetUserID(v int64) *CreationTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CreationTaskCreate) SetType(v string) *CreationTaskCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *CreationTaskCreate) SetTitle(v string) *CreationTaskCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *CreationTaskCreate) SetNillableTitle(v *string) *CreationTaskCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetInput sets the "input" field.
func (_c *CreationTaskCreate) SetInput(v string) *CreationTaskCreate {
	_c.mutation.SetInput(v)
	return _c
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (_c *CreationTaskCreate) SetNillableInput(v *string) *CreationTaskCreate {
	if v != nil {
		_c.SetInput(*v)
	}
	return _c
}

// SetOutput sets the "output" field.
func (_c *CreationTaskCreate) SetOutput(v string) *CreationTaskCreate {
	_c.mutation.SetOutput(v)
	return _c
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_c *CreationTaskCreate) SetNillableOutput(v *string) *CreationTaskCreate {
	if v != nil {
		_c.SetOutput(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *CreationTaskCreate) SetModel(v string) *CreationTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *CreationTaskCreate) SetNillableModel(v *string) *CreationTaskCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreationTaskCreate) SetCreatedAt(v time.Time) *CreationTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreationTaskCreate) SetNillableCreatedAt(v *time.Time) *CreationTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CreationTaskMutation object of the builder.
func (_c *CreationTaskCreate) Mutation() *CreationTaskMutation {
	return _c.mutation
}

// Save creates the CreationTask in the database.
func (_c *CreationTaskCreate) Save(ctx context.Context) (*CreationTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreationTaskCreate) SaveX(ctx context.Context) *CreationTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreationTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreationTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreationTaskCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := creationtask.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := creationtask.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := creationtask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreationTaskCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CreationTask.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "CreationTask.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := creationtask.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreationTask.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CreationTask.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := creationtask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CreationTask.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "CreationTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := creationtask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreationTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreationTask.created_at"`)}
	}
	return nil
}

func (_c *CreationTaskCreate) sqlSave(ctx context.Context) (*CreationTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreationTaskCreate) createSpec() (*CreationTask, *sqlgraph.CreateSpec) {
	var (
		_node = &CreationTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(creationtask.Table, sqlgraph.NewFieldSpec(creationtask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(creationtask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(creationtask.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(creationtask.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(creationtask.FieldInput, field.TypeString, value)
		_node.Input = value
	}
	if value, ok := _c.mutation.Output(); ok {
		_spec.SetField(creationtask.FieldOutput, field.TypeString, value)
		_node.Output = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(creationtask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(creationtask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreationTask.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreationTaskUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreationTaskCreate) OnConflict(opts ...sql.ConflictOption) *CreationTaskUpsertOne {
	_c.conflict = opts
	return &CreationTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreationTaskCreate) OnConflictColumns(columns ...string) *CreationTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreationTaskUpsertOne{
		create: _c,
	}
}

type (
	// CreationTaskUpsertOne is the builder for "upsert"-ing
	//  one CreationTask node.
	CreationTaskUpsertOne struct {
		create *CreationTaskCreate
	}

	// CreationTaskUpsert is the "OnConflict" setter.
	CreationTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CreationTaskUpsert) SetUserID(v int64) *CreationTaskUpsert {
	u.Set(creationtask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateUserID() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CreationTaskUpsert) AddUserID(v int64) *CreationTaskUpsert {
	u.Add(creationtask.FieldUserID, v)
	return u
}

// SetType sets the "type" field.
func (u *CreationTaskUpsert) SetType(v string) *CreationTaskUpsert {
	u.Set(creationtask.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateType() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldType)
	return u
}

// SetTitle sets the "title" field.
func (u *CreationTaskUpsert) SetTitle(v string) *CreationTaskUpsert {
	u.Set(creationtask.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateTitle() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldTitle)
	return u
}

// SetInput sets the "input" field.
func (u *CreationTaskUpsert) SetInput(v string) *CreationTaskUpsert {
	u.Set(creationtask.FieldInput, v)
	return u
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateInput() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldInput)
	return u
}

// ClearInput clears the value of the "input" field.
func (u *CreationTaskUpsert) ClearInput() *CreationTaskUpsert {
	u.SetNull(creationtask.FieldInput)
	return u
}

// SetOutput sets the "output" field.
func (u *CreationTaskUpsert) SetOutput(v string) *CreationTaskUpsert {
	u.Set(creationtask.FieldOutput, v)
	return u
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateOutput() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldOutput)
	return u
}

// ClearOutput clears the value of the "output" field.
func (u *CreationTaskUpsert) ClearOutput() *CreationTaskUpsert {
	u.SetNull(creationtask.FieldOutput)
	return u
}

// SetModel sets the "model" field.
func (u *CreationTaskUpsert) SetModel(v string) *CreationTaskUpsert {
	u.Set(creationtask.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationTaskUpsert) UpdateModel() *CreationTaskUpsert {
	u.SetExcluded(creationtask.FieldModel)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreationTaskUpsertOne) UpdateNewValues() *CreationTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(creationtask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreationTaskUpsertOne) Ignore() *CreationTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreationTaskUpsertOne) DoNothing() *CreationTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreationTaskCreate.OnConflict
// documentation for more info.
func (u *CreationTaskUpsertOne) Update(set func(*CreationTaskUpsert)) *CreationTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreationTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CreationTaskUpsertOne) SetUserID(v int64) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreationTaskUpsertOne) AddUserID(v int64) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateUserID() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *CreationTaskUpsertOne) SetType(v string) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateType() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *CreationTaskUpsertOne) SetTitle(v string) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateTitle() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateTitle()
	})
}

// SetInput sets the "input" field.
func (u *CreationTaskUpsertOne) SetInput(v string) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateInput() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateInput()
	})
}

// ClearInput clears the value of the "input" field.
func (u *CreationTaskUpsertOne) ClearInput() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.ClearInput()
	})
}

// SetOutput sets the "output" field.
func (u *CreationTaskUpsertOne) SetOutput(v string) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateOutput() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *CreationTaskUpsertOne) ClearOutput() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.ClearOutput()
	})
}

// SetModel sets the "model" field.
func (u *CreationTaskUpsertOne) SetModel(v string) *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationTaskUpsertOne) UpdateModel() *CreationTaskUpsertOne {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateModel()
	})
}

// Exec executes the query.
func (u *CreationTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreationTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreationTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreationTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreationTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreationTaskCreateBulk is the builder for creating many CreationTask entities in bulk.
type CreationTaskCreateBulk struct {
	config
	err      error
	builders []*CreationTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the CreationTask entities in the database.
func (_c *CreationTaskCreateBulk) Save(ctx context.Context) ([]*CreationTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreationTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreationTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreationTaskCreateBulk) SaveX(ctx context.Context) []*CreationTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreationTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreationTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreationTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreationTaskUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreationTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreationTaskUpsertBulk {
	_c.conflict = opts
	return &CreationTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreationTaskCreateBulk) OnConflictColumns(columns ...string) *CreationTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreationTaskUpsertBulk{
		create: _c,
	}
}

// CreationTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of CreationTask nodes.
type CreationTaskUpsertBulk struct {
	create *CreationTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CreationTaskUpsertBulk) UpdateNewValues() *CreationTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(creationtask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreationTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreationTaskUpsertBulk) Ignore() *CreationTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreationTaskUpsertBulk) DoNothing() *CreationTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreationTaskCreateBulk.OnConflict
// documentation for more info.
func (u *CreationTaskUpsertBulk) Update(set func(*CreationTaskUpsert)) *CreationTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreationTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CreationTaskUpsertBulk) SetUserID(v int64) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CreationTaskUpsertBulk) AddUserID(v int64) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateUserID() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *CreationTaskUpsertBulk) SetType(v string) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateType() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateType()
	})
}

// SetTitle sets the "title" field.
func (u *CreationTaskUpsertBulk) SetTitle(v string) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateTitle() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateTitle()
	})
}

// SetInput sets the "input" field.
func (u *CreationTaskUpsertBulk) SetInput(v string) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateInput() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateInput()
	})
}

// ClearInput clears the value of the "input" field.
func (u *CreationTaskUpsertBulk) ClearInput() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.ClearInput()
	})
}

// SetOutput sets the "output" field.
func (u *CreationTaskUpsertBulk) SetOutput(v string) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateOutput() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *CreationTaskUpsertBulk) ClearOutput() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.ClearOutput()
	})
}

// SetModel sets the "model" field.
func (u *CreationTaskUpsertBulk) SetModel(v string) *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CreationTaskUpsertBulk) UpdateModel() *CreationTaskUpsertBulk {
	return u.Update(func(s *CreationTaskUpsert) {
		s.UpdateModel()
	})
}

// Exec executes the query.
func (u *CreationTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreationTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreationTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreationTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
