// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/studiomodelconfig"
)

// StudioModelConfigUpdate is the builder for updating StudioModelConfig entities.
type StudioModelConfigUpdate struct {
	config
	hooks    []Hook
	mutation *StudioModelConfigMutation
}

// Where appends a list predicates to the StudioModelConfigUpdate builder.
func (_u *StudioModelConfigUpdate) Where(ps ...predicate.StudioModelConfig) *StudioModelConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StudioModelConfigUpdate) SetUserID(v int64) *StudioModelConfigUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudioModelConfigUpdate) SetNillableUserID(v *int64) *StudioModelConfigUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *StudioModelConfigUpdate) AddUserID(v int64) *StudioModelConfigUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *StudioModelConfigUpdate) SetConfig(v string) *StudioModelConfigUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *StudioModelConfigUpdate) SetNillableConfig(v *string) *StudioModelConfigUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StudioModelConfigUpdate) SetUpdatedAt(v time.Time) *StudioModelConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StudioModelConfigMutation object of the builder.
func (_u *StudioModelConfigUpdate) Mutation() *StudioModelConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StudioModelConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudioModelConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StudioModelConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudioModelConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StudioModelConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := studiomodelconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StudioModelConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(studiomodelconfig.Table, studiomodelconfig.Columns, sqlgraph.NewFieldSpec(studiomodelconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(studiomodelconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(studiomodelconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(studiomodelconfig.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(studiomodelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studiomodelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StudioModelConfigUpdateOne is the builder for updating a single StudioModelConfig entity.
type StudioModelConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudioModelConfigMutation
}

// SetUserID sets the "user_id" field.
func (_u *StudioModelConfigUpdateOne) SetUserID(v int64) *StudioModelConfigUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudioModelConfigUpdateOne) SetNillableUserID(v *int64) *StudioModelConfigUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *StudioModelConfigUpdateOne) AddUserID(v int64) *StudioModelConfigUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *StudioModelConfigUpdateOne) SetConfig(v string) *StudioModelConfigUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *StudioModelConfigUpdateOne) SetNillableConfig(v *string) *StudioModelConfigUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StudioModelConfigUpdateOne) SetUpdatedAt(v time.Time) *StudioModelConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StudioModelConfigMutation object of the builder.
func (_u *StudioModelConfigUpdateOne) Mutation() *StudioModelConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the StudioModelConfigUpdate builder.
func (_u *StudioModelConfigUpdateOne) Where(ps ...predicate.StudioModelConfig) *StudioModelConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StudioModelConfigUpdateOne) Select(field string, fields ...string) *StudioModelConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StudioModelConfig entity.
func (_u *StudioModelConfigUpdateOne) Save(ctx context.Context) (*StudioModelConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudioModelConfigUpdateOne) SaveX(ctx context.Context) *StudioModelConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StudioModelConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudioModelConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StudioModelConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := studiomodelconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StudioModelConfigUpdateOne) sqlSave(ctx context.Context) (_node *StudioModelConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(studiomodelconfig.Table, studiomodelconfig.Columns, sqlgraph.NewFieldSpec(studiomodelconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StudioModelConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studiomodelconfig.FieldID)
		for _, f := range fields {
			if !studiomodelconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != studiomodelconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(studiomodelconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(studiomodelconfig.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(studiomodelconfig.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(studiomodelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &StudioModelConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studiomodelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
