// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/studiomodelconfig"
)

// StudioModelConfigCreate is the builder for creating a StudioModelConfig entity.
type StudioModelConfigCreate struct {
	config
	mutation *StudioModelConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *StudioModelConfigCreate) SetUserID(v int64) *StudioModelConfigCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *StudioModelConfigCreate) SetConfig(v string) *StudioModelConfigCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *StudioModelConfigCreate) SetNillableConfig(v *string) *StudioModelConfigCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StudioModelConfigCreate) SetUpdatedAt(v time.Time) *StudioModelConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StudioModelConfigCreate) SetNillableUpdatedAt(v *time.Time) *StudioModelConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the StudioModelConfigMutation object of the builder.
func (_c *StudioModelConfigCreate) Mutation() *StudioModelConfigMutation {
	return _c.mutation
}

// Save creates the StudioModelConfig in the database.
func (_c *StudioModelConfigCreate) Save(ctx context.Context) (*StudioModelConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StudioModelConfigCreate) SaveX(ctx context.Context) *StudioModelConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudioModelConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudioModelConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StudioModelConfigCreate) defaults() {
	if _, ok := _c.mutation.Config(); !ok {
		v := studiomodelconfig.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := studiomodelconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StudioModelConfigCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "StudioModelConfig.user_id"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "StudioModelConfig.config"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StudioModelConfig.updated_at"`)}
	}
	return nil
}

func (_c *StudioModelConfigCreate) sqlSave(ctx context.Context) (*StudioModelConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StudioModelConfigCreate) createSpec() (*StudioModelConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &StudioModelConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(studiomodelconfig.Table, sqlgraph.NewFieldSpec(studiomodelconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(studiomodelconfig.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(studiomodelconfig.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(studiomodelconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudioModelConfig.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudioModelConfigUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *StudioModelConfigCreate) OnConflict(opts ...sql.ConflictOption) *StudioModelConfigUpsertOne {
	_c.conflict = opts
	return &StudioModelConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StudioModelConfigCreate) OnConflictColumns(columns ...string) *StudioModelConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StudioModelConfigUpsertOne{
		create: _c,
	}
}

type (
	// StudioModelConfigUpsertOne is the builder for "upsert"-ing
	//  one StudioModelConfig node.
	StudioModelConfigUpsertOne struct {
		create *StudioModelConfigCreate
	}

	// StudioModelConfigUpsert is the "OnConflict" setter.
	StudioModelConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *StudioModelConfigUpsert) SetUserID(v int64) *StudioModelConfigUpsert {
	u.Set(studiomodelconfig.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudioModelConfigUpsert) UpdateUserID() *StudioModelConfigUpsert {
	u.SetExcluded(studiomodelconfig.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *StudioModelConfigUpsert) AddUserID(v int64) *StudioModelConfigUpsert {
	u.Add(studiomodelconfig.FieldUserID, v)
	return u
}

// SetConfig sets the "config" field.
func (u *StudioModelConfigUpsert) SetConfig(v string) *StudioModelConfigUpsert {
	u.Set(studiomodelconfig.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *StudioModelConfigUpsert) UpdateConfig() *StudioModelConfigUpsert {
	u.SetExcluded(studiomodelconfig.FieldConfig)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudioModelConfigUpsert) SetUpdatedAt(v time.Time) *StudioModelConfigUpsert {
	u.Set(studiomodelconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudioModelConfigUpsert) UpdateUpdatedAt() *StudioModelConfigUpsert {
	u.SetExcluded(studiomodelconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StudioModelConfigUpsertOne) UpdateNewValues() *StudioModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StudioModelConfigUpsertOne) Ignore() *StudioModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudioModelConfigUpsertOne) DoNothing() *StudioModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudioModelConfigCreate.OnConflict
// documentation for more info.
func (u *StudioModelConfigUpsertOne) Update(set func(*StudioModelConfigUpsert)) *StudioModelConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudioModelConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *StudioModelConfigUpsertOne) SetUserID(v int64) *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *StudioModelConfigUpsertOne) AddUserID(v int64) *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudioModelConfigUpsertOne) UpdateUserID() *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetConfig sets the "config" field.
func (u *StudioModelConfigUpsertOne) SetConfig(v string) *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *StudioModelConfigUpsertOne) UpdateConfig() *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudioModelConfigUpsertOne) SetUpdatedAt(v time.Time) *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudioModelConfigUpsertOne) UpdateUpdatedAt() *StudioModelConfigUpsertOne {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StudioModelConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudioModelConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudioModelConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StudioModelConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StudioModelConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StudioModelConfigCreateBulk is the builder for creating many StudioModelConfig entities in bulk.
type StudioModelConfigCreateBulk struct {
	config
	err      error
	builders []*StudioModelConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the StudioModelConfig entities in the database.
func (_c *StudioModelConfigCreateBulk) Save(ctx context.Context) ([]*StudioModelConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StudioModelConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudioModelConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StudioModelConfigCreateBulk) SaveX(ctx context.Context) []*StudioModelConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudioModelConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudioModelConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudioModelConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudioModelConfigUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *StudioModelConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *StudioModelConfigUpsertBulk {
	_c.conflict = opts
	return &StudioModelConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StudioModelConfigCreateBulk) OnConflictColumns(columns ...string) *StudioModelConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StudioModelConfigUpsertBulk{
		create: _c,
	}
}

// StudioModelConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of StudioModelConfig nodes.
type StudioModelConfigUpsertBulk struct {
	create *StudioModelConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StudioModelConfigUpsertBulk) UpdateNewValues() *StudioModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudioModelConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StudioModelConfigUpsertBulk) Ignore() *StudioModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudioModelConfigUpsertBulk) DoNothing() *StudioModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudioModelConfigCreateBulk.OnConflict
// documentation for more info.
func (u *StudioModelConfigUpsertBulk) Update(set func(*StudioModelConfigUpsert)) *StudioModelConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudioModelConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *StudioModelConfigUpsertBulk) SetUserID(v int64) *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *StudioModelConfigUpsertBulk) AddUserID(v int64) *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudioModelConfigUpsertBulk) UpdateUserID() *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateUserID()
	})
}

// SetConfig sets the "config" field.
func (u *StudioModelConfigUpsertBulk) SetConfig(v string) *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *StudioModelConfigUpsertBulk) UpdateConfig() *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudioModelConfigUpsertBulk) SetUpdatedAt(v time.Time) *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudioModelConfigUpsertBulk) UpdateUpdatedAt() *StudioModelConfigUpsertBulk {
	return u.Update(func(s *StudioModelConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StudioModelConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StudioModelConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudioModelConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudioModelConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
